const TYPES = {
    APP: Symbol('APP'),
	TOOLS: {
		LOGGER: Symbol('TOOLS.LOGGER'),
		SERVER: Symbol('TOOLS.SERVER'),
		DOTENV: Symbol('TOOLS.DOTENV'),
		EVENT_EMITTER: Symbol('TOOLS.EVENT_EMITTER'),
	},
	UI: Symbol('UI'),
	CONTROLLER: {
		ROOM: Symbol('CONTROLLER.ROOM'),
		PLAYER: Symbol('CONTROLLER.PLAYER'),
		VALIDATOR: Symbol('CONTROLLER.VALIDATOR'),
		CODE_GENERATOR: Symbol('CONTROLLER.CODE_GENERATOR'),
		MSG_CODER: Symbol('CONTROLLER.MSG_CODER'),
		GAME: Symbol('CONTROLLER.GAME'),
		GAME_MAP: Symbol('CONTROLLER.GAME_MAP'),
		GAME_LOOP: Symbol('CONTROLLER.GAME_LOOP'),
	},
	MODEL: {
		ROOM: Symbol('MODEL.ROOM'),
		PLAYER: Symbol('MODEL.PLAYER'),
		GAME: Symbol('MODEL.GAME'),
		GAME_MAP: Symbol('MODEL.GAME_MAP'),
		GAME_LOOP: Symbol('MODEL.GAME_LOOP'),
	}
}

export default TYPES


